#!/usr/bin/env python3
"""
Rivals - Professional JSON Processor & Analyzer
Handles complex JSON structures, data enrichment, and reporting
Author: KercX
"""

import json
import csv
import sys
import os
import hashlib
from datetime import datetime
from typing import Dict, List, Any, Optional
import argparse
from collections import Counter, defaultdict
import pandas as pd

class RivalsJSONProcessor:
    """Advanced JSON processor for OSINT data"""
    
    def __init__(self, input_file: str = None, data: dict = None):
        self.input_file = input_file
        self.data = data or {}
        self.stats = {
            "processed_at": datetime.now().isoformat(),
            "total_platforms": 0,
            "found_profiles": 0,
            "errors": 0
        }
        
    def load_json(self) -> bool:
        """Load JSON from file"""
        try:
            if self.input_file and os.path.exists(self.input_file):
                with open(self.input_file, 'r', encoding='utf-8') as f:
                    self.data = json.load(f)
                return True
        except Exception as e:
            print(f"❌ Error loading JSON: {e}")
        return False
    
    def analyze_results(self) -> Dict:
        """Analyze scan results and extract insights"""
        if not self.data:
            return {}
        
        analysis = {
            "username": self.data.get("username", "unknown"),
            "timestamp": self.data.get("timestamp", datetime.now().isoformat()),
            "scan_summary": self.data.get("summary", {}),
            "insights": {}
        }
        
        # Analyze platforms
        platforms = self.data.get("platforms", [])
        analysis["total_platforms"] = len(platforms)
        
        # Extract existing profiles
        found = [p for p in platforms if p.get("exists", False)]
        analysis["found_profiles"] = found
        analysis["found_count"] = len(found)
        
        # Group by response time
        fast_profiles = [p for p in found if p.get("response_time_ms", 999) < 500]
        slow_profiles = [p for p in found if p.get("response_time_ms", 0) > 1000]
        
        analysis["insights"]["fast_response"] = len(fast_profiles)
        analysis["insights"]["slow_response"] = len(slow_profiles)
        
        # Calculate average response time
        if platforms:
            avg_time = sum(p.get("response_time_ms", 0) for p in platforms) / len(platforms)
            analysis["insights"]["avg_response_ms"] = round(avg_time, 2)
        
        return analysis
    
    def generate_report(self, format: str = "json") -> str:
        """Generate human-readable report"""
        analysis = self.analyze_results()
        
        if format == "json":
            return json.dumps(analysis, indent=2)
        
        # Text format
        report = f"""
╔══════════════════════════════════════════════════════════════╗
║                    RIVALS OSINT REPORT                        ║
║                      Generated by KercX                       ║
╚══════════════════════════════════════════════════════════════╝

📊 SCAN INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Username:        {analysis.get('username', 'N/A')}
  Scan Date:       {analysis.get('timestamp', 'N/A')}
  Total Platforms: {analysis.get('total_platforms', 0)}
  Found Profiles:  {analysis.get('found_count', 0)}

🎯 FOUND PROFILES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        for profile in analysis.get('found_profiles', []):
            report += f"  ✓ {profile.get('name', 'Unknown'):15} → {profile.get('url', 'N/A')}\n"
            report += f"    ⚡ Response: {profile.get('response_time_ms', 0)}ms\n"
        
        report += f"""
⚡ PERFORMANCE METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Fast Responses (<500ms):  {analysis['insights'].get('fast_response', 0)}
  Slow Responses (>1000ms): {analysis['insights'].get('slow_response', 0)}
  Average Response Time:    {analysis['insights'].get('avg_response_ms', 0)}ms

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Report generated by Rivals OSINT Tool
  Author: KercX | GitHub: @KercX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        return report
    
    def export_to_csv(self, output_file: str) -> bool:
        """Export results to CSV format"""
        try:
            platforms = self.data.get("platforms", [])
            if not platforms:
                return False
            
            with open(output_file, 'w', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=["name", "url", "exists", "status_code", "response_time_ms"])
                writer.writeheader()
                for p in platforms:
                    writer.writerow(p)
            return True
        except Exception as e:
            print(f"❌ CSV export failed: {e}")
            return False
    
    def extract_emails_from_text(self) -> List[str]:
        """Extract emails from JSON text data"""
        import re
        text = json.dumps(self.data)
        email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
        return list(set(re.findall(email_pattern, text)))
    
    def find_social_links(self) -> Dict[str, List[str]]:
        """Extract social media links from results"""
        social_domains = {
            "twitter": ["twitter.com", "x.com"],
            "instagram": ["instagram.com"],
            "facebook": ["facebook.com", "fb.com"],
            "linkedin": ["linkedin.com"],
            "github": ["github.com"],
            "youtube": ["youtube.com", "youtu.be"],
            "tiktok": ["tiktok.com"],
            "reddit": ["reddit.com"]
        }
        
        found_links = defaultdict(list)
        text = json.dumps(self.data)
        
        for platform, domains in social_domains.items():
            for domain in domains:
                pattern = rf'https?://(?:www\.)?{domain}/[^\s"\'<>]+'
                matches = re.findall(pattern, text)
                found_links[platform].extend(matches)
        
        return dict(found_links)

def main():
    parser = argparse.ArgumentParser(description='Rivals JSON Processor')
    parser.add_argument('-i', '--input', required=True, help='Input JSON file')
    parser.add_argument('-o', '--output', help='Output file')
    parser.add_argument('-f', '--format', choices=['json', 'txt', 'csv'], default='txt', help='Output format')
    parser.add_argument('--extract-emails', action='store_true', help='Extract emails from data')
    parser.add_argument('--find-links', action='store_true', help='Find social media links')
    
    args = parser.parse_args()
    
    processor = RivalsJSONProcessor(input_file=args.input)
    
    if not processor.load_json():
        sys.exit(1)
    
    if args.extract_emails:
        emails = processor.extract_emails_from_text()
        print("\n📧 Found Emails:")
        for email in emails:
            print(f"  ✉️  {email}")
    
    elif args.find_links:
        links = processor.find_social_links()
        print("\n🔗 Social Media Links:")
        for platform, urls in links.items():
            print(f"\n  📱 {platform.upper()}:")
            for url in urls[:5]:  # Limit to 5 per platform
                print(f"    → {url}")
    
    else:
        report = processor.generate_report(format=args.format)
        
        if args.output:
            with open(args.output, 'w') as f:
                f.write(report)
            print(f"✅ Report saved to: {args.output}")
        else:
            print(report)

if __name__ == "__main__":
    main()
